const PREFIX = "@@analytics/";

export const ANALYTICS_INIT = `${PREFIX}ANALYTICS_INIT`;
export const RESET_NOTIFICATION = `${PREFIX}RESET_NOTIFICATION`;
export const ANALYTICS_FAILURE = `${PREFIX}ANALYTICS_FAILURE`;

export const GET_ANALYTICS_SUCCESS = `$${PREFIX}GET_ANALYTICS_SUCCESS`;
