const PREFIX = "@@auth/";

export const AUTH_INIT = `${PREFIX}AUTH_INIT`;
export const AUTH_SUCCESS = `${PREFIX}AUTH_SUCCESS`;
export const AUTH_FAILURE = `${PREFIX}AUTH_FAILURE`;
export const GET_USER_SUCCESS = `${PREFIX}GET_USER_SUCCESS`;
export const UPDATE_USER_SUCCESS = `${PREFIX}UPDATE_USER_SUCCESS`;
export const GET_COMPLICATIONS_SUCCESS = `${PREFIX}GET_COMPLICATIONS_SUCCESS`;

export const RESET_NOTIFICATION = `${PREFIX}RESET_NOTIFICATION`;
