const PREFIX = "@@stress/";

export const STRESS_INIT = `${PREFIX}STRESS_INIT`;
export const RESET_NOTIFICATION = `${PREFIX}RESET_NOTIFICATION`;
export const STRESS_INITIATE = `${PREFIX}STRESS_INITIATE`;
export const PREDICT_STRESS_SUCCESS = `${PREFIX}PREDICT_STRESS_SUCCESS`;
export const STRESS_FAILURE = `${PREFIX}STRESS_FAILURE`;
export const STRESS_PLAN_SUCCESS = `${PREFIX}STRESS_PLAN_SUCCESS`;
